replicaCount: 1

image:
  repository: gmarialva/ezopsapi
  pullPolicy: IfNotPresent
  tag: "1.0"

imagePullSecrets: 
  - name: dockerhub
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

namespace:
  name: ezops

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

livenessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 90
  periodSeconds: 30
readinessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 90
  periodSeconds: 30

service:
  name: http
  type: ClusterIP
  port: 5000
  containerPort: 3000
  protocol: TCP
  targetPort: http

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

configMap:
  create: true
  name: "api"
  data:
    DB_USER: api
    DB_HOST: postgres
    DB_PORT: "5432"
    DB_NAME: "ezopsapi"

secret:
  create: true
  name: "api"
  data: 
    DB_PASSWORD: password

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
